---
version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
# JAVASCRIPT
  - package-ecosystem: npm
    directory: "/javascript"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "01:00"
    open-pull-requests-limit: 50
    update-types: minor, patch
    pull-request-branch-name:
      separator: _
# PYTHON (PIP AND POETRY)
  - package-ecosystem: pip
    directory: "/python"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "01:00"
    open-pull-requests-limit: 50
    update-types: patch
    pull-request-branch-name:
      separator: _
#    groups:
#      production-dependencies:
#        dependency-type: production
#      development-dependencies:
#        dependency-type: development
#      python-packages:



