---
version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
# JAVASCRIPT
  - package-ecosystem: npm
    directory: "/javascript"
    schedule:
      interval: "weekly"
#      day: "monday"
    open-pull-requests-limit: 20
    pull-request-branch-name:
      separator: _
# PYTHON (PIP AND POETRY)
  - package-ecosystem: pip
    directory: "/python"
    schedule:
      interval: "weekly"
  #      day: "monday"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: _


